[build]
  base = "frontend"
  command = "ng build"
  publish = "dist/cash-register-angular-app/browser"

[[plugins]]
  package = "@netlify/angular-runtime"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
